### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_linear'

### ISSUE THREAD

**Issue by nickppbd** [emedvedev/attention-ocr#62]
C:\Users\username>aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecords
Traceback (most recent call last):
  File "C:\Python\Scripts\aocr-script.py", line 11, in <module>
    load_entry_point('aocr==0.6.0', 'console_scripts', 'aocr')()
  File "C:\Python\lib\site-packages\pkg_resources\__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python\lib\site-packages\pkg_resources\__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "C:\Python\lib\site-packages\pkg_resources\__init__.py", line 2408, in load
    return self.resolve()
  File "C:\Python\lib\site-packages\pkg_resources\__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Python\lib\site-packages\aocr-0.6.0-py3.6.egg\aocr\__main__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Python\lib\site-packages\aocr-0.6.0-py3.6.egg\aocr\model\model.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Python\lib\site-packages\aocr-0.6.0-py3.6.egg\aocr\model\seq2seq_model.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Python\lib\site-packages\aocr-0.6.0-py3.6.egg\aocr\model\seq2seq.py", line 79, in <module>
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_linear'

What should I do?

**Comment by emedvedev** [comment]
Hi! Which version of Tensorflow are you running?

**Comment by emedvedev** [comment]
I think it's fixed now, please try 0.6.1.

**Comment by nickppbd** [comment]
I use 1.5.0 tensorflow version.
What means 'please try 0.6.1.' ?

**Comment by emedvedev** [comment]
I’ve just released a new package version, 0.6.1, so it could be fixed there (or just on master), but not entirely sure, since I haven’t tried TF 1.5.0 yet. Will try tomorrow and report.

**Comment by emedvedev** [comment]
@nickppbd released another version, 0.6.2, and verified that it works with 1.5.0. Please try updating from `master` (or pip) and running again.

**Comment by nickppbd** [comment]
Thanks, I'll do the new version and report:)

**Comment by nickppbd** [comment]
@emedvedev I tried 'pip uninstall aocr and pip install aocr' and do this below.

**** means I hide for security.
C:\Users\****>aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecor
2018-02-02 09:45:21.070347: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-02-02 09:45:21,059 root  INFO     Building a dataset from ./datasets/annotations-training.txt.
2018-02-02 09:45:21,059 root  INFO     Output file: ./datasets/training.tfrecor
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\aocr.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\aocr\__main__.py", line 219, in main
    dataset.generate(parameters.annotations_path, parameters.output_path, parameters.log_step, parameters.force_uppercase, parameters.save_filename)
  File "c:\python\lib\site-packages\aocr\util\dataset.py", line 19, in generate
    writer = tf.python_io.TFRecordWriter(output_path)
  File "c:\python\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "c:\python\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: ./datasets/training.tfrecor : \udcc1\udcf6\udcc1\udca4\udcb5\udcc8 \udcb0\udce6\udcb7θ\udca6 ã\udcc0\udcbb \udcbc\udcf6 \udcbe\udcf8\udcbd\udcc0\udcb4ϴ\udcd9.
; No such process

**Comment by nickppbd** [comment]
@emedvedev I remove anaconda and reinstall tensorflow from pip and Do this below.

PS C:\> pip uninstall acor
Uninstalling acor-1.1.1:
  c:\python\lib\site-packages\acor-1.1.1.dist-info\description.rst
  c:\python\lib\site-packages\acor-1.1.1.dist-info\installer
  c:\python\lib\site-packages\acor-1.1.1.dist-info\metadata
  c:\python\lib\site-packages\acor-1.1.1.dist-info\metadata.json
  c:\python\lib\site-packages\acor-1.1.1.dist-info\record
  c:\python\lib\site-packages\acor-1.1.1.dist-info\top_level.txt
  c:\python\lib\site-packages\acor-1.1.1.dist-info\wheel
  c:\python\lib\site-packages\acor\__init__.py
  c:\python\lib\site-packages\acor\__pycache__\__init__.cpython-36.pyc
  c:\python\lib\site-packages\acor\__pycache__\acor.cpython-36.pyc
  c:\python\lib\site-packages\acor\_acor.cp36-win_amd64.pyd
  c:\python\lib\site-packages\acor\acor.py
Proceed (y/n)? y
  Successfully uninstalled acor-1.1.1
PS C:\> pip install acor
Collecting acor
Requirement already satisfied: numpy in c:\python\lib\site-packages (from acor)
Installing collected packages: acor
Successfully installed acor-1.1.1
PS C:\> aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecords
2018-02-02 13:24:02.063281: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-02-02 13:24:02,059 root  INFO     Building a dataset from ./datasets/annotations-training.txt.
2018-02-02 13:24:02,059 root  INFO     Output file: ./datasets/training.tfrecords
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\aocr.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\aocr\__main__.py", line 219, in main
    dataset.generate(parameters.annotations_path, parameters.output_path, parameters.log_step, parameters.force_uppercase, parameters.save_filename)
  File "c:\python\lib\site-packages\aocr\util\dataset.py", line 19, in generate
    writer = tf.python_io.TFRecordWriter(output_path)
  File "c:\python\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "c:\python\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: ./datasets/training.tfrecords : \udcc1\udcf6\udcc1\udca4\udcb5\udcc8 \udcb0\udce6\udcb7θ\udca6 ã\udcc0\udcbb \udcbc\udcf6 \udcbe\udcf8\udcbd\udcc0\udcb4ϴ\udcd9.
; No such process

**Comment by emedvedev** [comment]
It's a different error already. I think your paths should be different on Windows: try "datasets/annotations-training.txt datasets/training.tfrecord" for relative paths, without `./` in the beginning.

Closing the issue, because the original problem has been resolved, but feel free to comment or open new ones!
